# Reusable workflow for releases; to eject, you can replace this file with
# https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/release.yml
name: Release
on: ["push", "pull_request"]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: |
          npx turbo run test
          ls
          cd packages/is-even
          ls
          cd coverage
          ls
      - name: Subproject Is Even
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          flag-name: is-even
          path-to-lcov: ./packages/is-even/coverage/lcov.info
      - name: Subproject Is Odd
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          flag-name: is-odd
          path-to-lcov: ./packages/is-oden/coverage/lcov.info
      - name: Subproject Server
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          flag-name: server
          path-to-lcov: ./packages/server/coverage/lcov.info
