# Reusable workflow for releases; to eject, you can replace this file with
# https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/release.yml
name: Release
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - is-even
          - is-odd
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install
        run: yarn

      - name: Test ${{ matrix.test_number }}
        run: yarn test
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: ${{ matrix.package }}
          path-to-lcov: ./packages/${{ matrix.package }}/coverage/lcov.info
          parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "run-1,run-2"
